"""create pilot records

Revision ID: a5751f541400
Revises:
Create Date: 2026-09-23 20:57:55.789158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5751f541400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilot_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.String(length=50), nullable=False),
    sa.Column('crop', sa.String(length=200), nullable=False),
    sa.Column('image_reference', sa.String(length=255), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('actual_diagnosis', sa.Text(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('recommendation_followed', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_record')
    # ### end Alembic commands ###
